enum IngredientType { STRONG_ALCOHOLIC_DRINK, WEAK_ALCOHOLIC_DRINK, NON_ALCOHOLIC_DRINK, STRONG_FLAVOUR }
enum GeneratorBehaviourType {UNDER_18, NON_ALCOHOLIC, DEFAULT, HUGO_ADVERT, WATER_ONLY, DEATH}